# Generated by Django 5.0 on 2024-01-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Titre')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.author')),
            ],
        ),
    ]
