# Generated by Django 5.0 on 2024-01-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('apply_promo_code', 'peut appliquer des réductions')], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
    ]
